version: '3'
services:
  hellodockertools:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '80'
networks:
  default:
    external:
      name: <span data-ttu-id="ff415-101">Translator adres√≥w sieciowych</span><span class="sxs-lookup"><span data-stu-id="ff415-101">nat</span></span>